default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_NAME"] %>
  encoding: unicode
  port: 5432
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


test:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: test_<%= ENV["DB_NAME"] %>
  encoding: unicode
  port: 5432
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>